### ISSUE TITLE
general todo list

### ISSUE THREAD

**Issue by ConorSheehan1** [ConorSheehan1/advent_of_code_2018#1]
- [x] use dayA input by default
- [x] add travis? run specs? run rubocop? 
- [x] get yard to recognize aoc as ruby file
- [x] add specs for aoc thor functions
- [ ] wrap src scripts in class for better docs? group methods by day using class
